apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gym-call-agent
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: bidetking.ddns.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gym-call-agent
                port:
                  number: 80